name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached Primes
        id: cache-primes-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ runner.os }}-primes
      .
      . //intermediate workflow steps
      .
      - name: Save Primes
        id: cache-primes-save
        uses: actions/cache/save@v3
        with:
          path: |
            path/to/dependencies
            some/other/dependencies
          key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}